name: MetroPulse CI

on:
  pull_request:
    branches:
      - main

jobs:
  basic-checks:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Get repository code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Check Python syntax
        run: python -m compileall src orchestration

      - name: Check dbt connection
        working-directory: metropulse_dbt
        run: dbt debug --profiles-dir ../.github/dbt-ci

      - name: Build and test dbt project
        working-directory: metropulse_dbt
        run: dbt build --profiles-dir ../.github/dbt-ci